### ISSUE TITLE
Inline `GroupIndex` and `Height`

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#111]
These types are wrappers around primitive type (`Int`) and can be inlined.

**Comment by simerplaha** [comment]
@tdroxler value classes are awesome! Can't believe I've never heard of them before. Thank you.

We might still need to add the inline flags to the build so inlining works for things that are annotated `@inline` and we get compiler optimisations like the following

> inlined org/alephium/explorer/api/model/GroupIndex$.unsafe (the callee is a small trivial method). Before: 77 ins, after: 93 ins. 
> inlined org/alephium/explorer/api/model/Height$.unsafe (the callee is a small trivial method). Before: 23 ins, after: 39 ins.

WDYT, submit a PR just for the flags?

I've noticed that inlining increases build times and messes up debuggers so I normally disable it locally when in dev more and leave it on when benchmarking and for production releases.

**Comment by tdroxler** [comment]
Sure let's add the flags :rocket:

**Comment by tdroxler** [comment]
@simerplaha did we add the flag? I can't remember.

**Comment by simerplaha** [comment]
Yes we still do so our `@inline` annotations get applied. If I remember correctly, there was some dependency issue that was was failing the build with the inline flags. 

But yes we still need this, very low priority though.
