### ISSUE TITLE
Use partial index on `block_headers` table where `main_chain = true`

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#123]
Parent task: #120

Target table: `block_headers`
 
## Checks to perform after update

- [ ] Ensure that queries to this table are still using `INDEX ONLY SCAN`
- [ ] Benchmarks should produce better or similar results

**Comment by tdroxler** [comment]
@simerplaha is it still relevant?

**Comment by simerplaha** [comment]
Think this might be an old duplicate of one of the double checking tasks - #208 #283 and probably falls under few other double checking tasks. 

We can close this.
