### ISSUE TITLE
Add `amount` in `SweepAddressTransaction`

### ISSUE THREAD

**Issue by nop33** [alephium/explorer-backend#144]
Would it be possible to add the `amount` in `SweepAddressTransaction`, so that the wallet can display the amount of the pending sweep transactions? At the moment there is no way to know how much amount each “consolidation” (aka “sweep”) transaction includes.

**Comment by tdroxler** [comment]
@nop33 do you still need this? if yes can you recreate the issue in the `alephium` repo? :)

**Comment by nop33** [comment]
This was implemented already, the issue should have been closed..! Thanks for closing it!
