### ISSUE TITLE
Database connection created by tests should be closed after each run

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#146]
# Issue 
Our test cases do not close connections created after each test run. 

We have a total of 70 test cases so it not a problem yet.

# Test
Quick test demo the error 

```scala
(1 to 300) foreach {
  _ =>
    val fixture = new Fixture {}
    import fixture.config.profile.api._
    fixture.run(fixture.blockDepsTable.result).futureValue
}
```
Errors the following after 214 iterations.

> java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[49.957s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.

**Comment by simerplaha** [comment]
Added two demo versions. 

Both versions require renaming `DBRunner.run` to `DBRunner.runAction` to fix conflicting names with ScalaTest's internal `run` function. 

## Demo version 1: Branch [#146_test_cases](https://github.com/alephium/explorer-backend/tree/%23146_test_cases) 

Removes traits inheritance to make the test-cases self contained.

```scala
it should "do something" in {
  //Calls TestDBRunner with tables needed for this test. DB connection is closed after the test is completed by `using`.
  using(TestDBRunner(BlockHeaderSchema.table, TransactionSchema.table)) { implicit runner =>
    val blocks       = runAction(...).futureValue
    val transactions = runAction(...).futureValue
   // ....
  }
}
```

See change applied to one test-case - [BlockDepQueriesSpec](https://github.com/alephium/explorer-backend/blob/40556c0246b73ebba6afa95365345a9cf6dd1f9f/app/src/test/scala/org/alephium/explorer/persistence/queries/BlockDepQueriesSpec.scala)

## Demo version 2: Branch [#146_test_cases_rename](https://github.com/alephium/explorer-backend/tree/%23146_test_cases_rename) 

Uses how we currently write tests using `Fixture`s which creates all the tables (even the ones not required by the test).

```scala
it should "do something" in {
  //DatabaseFixture implements AutoCloseable so the DB connection is closed after test is complete by `using`. 
  using(new Fixture) { fixture =>
    import fixture._
    val blocks       = runAction(...).futureValue
    val transactions = runAction(...).futureValue    
    //...
  }
}
class Fixture extends DatabaseFixture with DBRunner with Generators
```

See change applied to one test-case - [BlockDepQueriesSpec](https://github.com/alephium/explorer-backend/blob/e813a7614d7d0311a9b040ff303ac98127d5f6e9/app/src/test/scala/org/alephium/explorer/persistence/queries/BlockDepQueriesSpec.scala)

**Comment by polarker** [comment]
Thanks for the demo code. I feel that it is possible to do something like the following so that each test can create and destroy tables automatically. We use this approach for the full node's test actor systems: https://github.com/alephium/alephium/blob/master/util/src/test/scala/org/alephium/util/AlephiumActorSpec.scala#L45-L58
```
class MyTest extends DBFixture {
  // all of the existing tests
}

trait DBFixture extends BeforeAndAfterEach {
  implicit def runner: T = ...

  override def beforeEach(): Unit = {
    // initialize all connections and tables
  }

  override def afterEach(): Unit = {
    // close all tables and connections
  }
  
  def runAction(action: T): S = ???
}
```

**Comment by simerplaha** [comment]
Haha see I knew you wouldn't like my solutions. Know you too well now Cheng.

`BeforeAndAfterEach` - pretty standard way of writing tests in Java.

In our Slack convo I mentioned that the approach using inheritance is something that I try to avoid which is what you suggested here. Reason being each test is not self-contained (part of the logic is in that `DBFixture` trait) which will become problematic as the number of tests grows and we are making every test to create all tables even if the test only requires few. 

Regardless, will go with your suggested approach.

**Comment by polarker** [comment]
I did not get what do you mean by using inheritance initially, but now I see it.

If you want to create a sublist of tables, you could override the list of tables in the inheritance.
