### ISSUE TITLE
Use IndexedSeq or ArraySeq or AVector instead of Seq for performance

### ISSUE THREAD

**Issue by polarker** [alephium/explorer-backend#148]

**Comment by polarker** [comment]
The new ArraySeq might be even better I guess.

**Comment by tdroxler** [comment]
[slick is using Vector](https://github.com/slick/slick/blob/56ea2b86064082b64684ea700871ec39a041a69e/slick/src/main/scala/slick/jdbc/StaticQuery.scala#L91-L104) for their api we use.

I'm not a collection expert, but should I give a try with `Vector` or try to override stuff to have `ArraySeq`?

**Comment by polarker** [comment]
1. We'd better make it explicit, either `Vector` or `ArraySeq`
2. I prefer `ArraySeq`. This benchmark done years ago is still relevant: https://www.lihaoyi.com/post/BenchmarkingScalaCollections.html#arrays-are-great

**Comment by tdroxler** [comment]
:+1: I'll  give a try with `ArraySeq`

**Comment by polarker** [comment]
If it's not possible, then we have to go with `Vector` I guess

**Comment by tdroxler** [comment]
I did a quick try + benchmarks [here](https://github.com/alephium/explorer-backend/commit/af8bb35d) The difference is not huge, but overall it's a bit better that using `Seq`, this is only one query, if everything is `ArraySeq` it could indeed improve the overall thing.
Here are several runs:

```
DBBenchmark.getTransactionsByAddressSQL          thrpt       116.735          ops/s
DBBenchmark.getTransactionsByAddressSQLArraySeq  thrpt       167.559          ops/s
```
```
DBBenchmark.getTransactionsByAddressSQL          thrpt       169.956          ops/s
DBBenchmark.getTransactionsByAddressSQLArraySeq  thrpt       176.694          ops/s
```
```
DBBenchmark.getTransactionsByAddressSQL          thrpt       177.880          ops/s
DBBenchmark.getTransactionsByAddressSQLArraySeq  thrpt       188.152          ops/s
```
```
DBBenchmark.getTransactionsByAddressSQL          thrpt       125.048          ops/s
DBBenchmark.getTransactionsByAddressSQLArraySeq  thrpt       127.621          ops/s
```
```
DBBenchmark.getTransactionsByAddressSQL          thrpt       171.913          ops/s
DBBenchmark.getTransactionsByAddressSQLArraySeq  thrpt       174.093          ops/s
```
```
DBBenchmark.getTransactionsByAddressSQL          thrpt       170.659          ops/s
DBBenchmark.getTransactionsByAddressSQLArraySeq  thrpt       166.381          ops/s
```
```
DBBenchmark.getTransactionsByAddressSQL          thrpt       169.093          ops/s
DBBenchmark.getTransactionsByAddressSQLArraySeq  thrpt       175.645          ops/s
```

**Comment by tdroxler** [comment]
[I override the slick function](https://github.com/slick/slick/blob/56ea2b86064082b64684ea700871ec39a041a69e/slick/src/main/scala/slick/jdbc/StaticQuery.scala#L91-L104) to have directly `ArraySeq` [here](https://github.com/alephium/explorer-backend/blob/af8bb35d54efc220c74ba37afd4fea131ad20a86/app/src/main/scala/org/alephium/explorer/util/SlickUtil.scala#L72-L94)

**Comment by polarker** [comment]
Not only SQL queries, but the other code can also benefit from this. It sound like a good change to me!
