### ISSUE TITLE
Rename `order` table fields

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#157]
`order` is a sql key-word, we need to make sore we don't use it. In few place we also use `index`...which is also a key word ^^ let's use something meaningful: `tx_order` etc

**Comment by polarker** [comment]
@tdroxler shall we include this change for the incoming release?

**Comment by tdroxler** [comment]
yep good idea, I'll tackle this now

**Comment by simerplaha** [comment]
`timestamp` is another reserved keyword. 

`version` (in `block_headers`) although mentioned in the [docs](https://www.postgresql.org/docs/current/sql-keywords-appendix.html) as not reserved is a keyword in SQL. Maybe still worth renaming just incase :S

**Comment by tdroxler** [comment]
yeah let's play it safe and rename `timestamp` -> `block_timestamp` and `version` -> `block_version`
