### ISSUE TITLE
Fix insertion of big block

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#160]
When we insert a big block, we create too many bind variable for postgres' prepared statement.
The issue is shown in that branch: `feature/insert-big-block`
just run: `app/testOnly org.alephium.explorer.persistence.dao.BlockDaoSpec -- -z "insert big block"`

**Comment by simerplaha** [comment]
Hey @tdroxler, just like how you found, Postgres allows `32767` parameters per query. 

This commit fixes this by adding the ability to split a query into 2 or more queries when parameter size grows over `32767` (configurable). 

Eg: for queries with one parameter per row `INSERT INTO TABLE values (?)`
- if parameter count is `32767 + 1`, first query gets build with `32767` parameters and second one gets `1`. 
    - Maybe it's more efficient to split this in two queries of equal sizes `(32767 + 1) / 2`. This need benchmarking. The current solution is basic. 
- if parameter count is `32767 * 7`, seven queries get build with `32767` parameters each. 

Alternative a simpler approach would be to revert back to how Slick's typed queries did batch insert i.e. single row per insert. 

```
BEGIN;
INSERT INTO TABLE values (?, ?, ?, ...);
INSERT INTO TABLE values (?, ?, ?, ...);
COMMIT;
```

I can run benchmarks to see if there is a performance difference. What do you think?

**Comment by tdroxler** [comment]
The error was:  `Tried to send an out-of-range integer as a 2-byte value` and I end up on [that issue](https://github.com/pgjdbc/pgjdbc/issues/1311) where we can see that actually `Short.MaxValue = 32767`

Let's start with your solution and as we discussed, if we feel at some point that we need some optimization we can run the various benchmarks.
