### ISSUE TITLE
Add getInfosTotalTransactions and getInfosChains

### ISSUE THREAD

**Issue by lf94** [alephium/explorer-backend#169]
Depended by https://github.com/alephium/explorer/issues/32

**Comment by nop33** [comment]
Could you please be more specific as to why this is needed? Thanks!

**Comment by lf94** [comment]
Absolutely!

Currently `alephium-js` (or more appropriately, `explorer-backend`) only exposes the following *which satisfy the needs of the issue*:

```
    client?.charts
      .getChartsHashrates({
        fromTs: new Date().getTime() - ONE_DAY,
        toTs: new Date().getTime(),
        interval: 'hourly'
      })
      .then((res) => res.json())
      .then((value) => setHashrate(value[0] || ''))

    client?.infos
      .getInfosHeights()
      .then((res) => res.json())
      .then((value) => setBlocks(value[0] || ''))

    client?.infos
      .getInfosSupplyTotalAlph()
      .then((res) => res.text())
      .then((value) => setSupply(value))

    client?.infos
      .getInfosSupplyCirculatingAlph()
      .then((res) => res.text())
      .then((value) => setCirculating(value))
```

The original issue though also requires total transactions transacted, and the number of current chains and max chains. I've opted to stay within the naming scheme of "getInfos<Name>":

```
    client?.infos
      .getInfosTotalTransactions()
      .then((res) => res.text())
      .then((value) => setTransactions(value))
    setTransactions('')

    client?.infos
      .getInfosChains()
      .then((res) => res.text())
      .then((value) => setChains(value))

```

And yeah, that's it. I've pinged @tdroxler for advice and begun to figure out how to implement this in `explorer-backend`. From what I understand, the following needs to happen:

* Calculate the total transactions by taking the sum of all `txs_count` from `BlockHeader` table.
  * Store this value in a new table so it's not constantly recalculated
  * Make an endpoint which simply reads from this table

`TokenSupplyService` appears to be a very good starting point in what's needed so I'm using it to learn from.

I have not looked into `getInfosChains` yet - doing one thing at a time!

**Comment by nop33** [comment]
Not sure if this PR satisfies all the needs of this issue: https://github.com/alephium/js-sdk/pull/88/files

**Comment by lf94** [comment]
@nop33 yep! That does, thank you.
