### ISSUE TITLE
DRY in the OpenAPI spec file

### ISSUE THREAD

**Issue by lf94** [alephium/explorer-backend#172]
Currently it repeats *a lot* for the responses. This can be corrected with https://swagger.io/docs/specification/describing-responses/#reuse .

**Comment by tdroxler** [comment]
We don't change manually the openapi file, it's auto-generated from the code with [tapir](https://github.com/softwaremill/tapir), I would need to check in their source code if we can do what you propose.

**Comment by lf94** [comment]
If that's the case then I think this issue can be closed: my main concern was making it easier to read, but the original source its derived from is better to read. I'll close.
