### ISSUE TITLE
Block `main_chain` count query should populate in read-only

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#186]
PR #180 (Cached `main_chain` count query) does not solve for `read-only` mode.

**Comment by tdroxler** [comment]
One idea could be to add those timeout value in the config file and pass different value if it's read-only or not.

**Comment by polarker** [comment]
Why the cache is different for `read-only` and `write` mode?

**Comment by tdroxler** [comment]
for the block count, in the `write` mode, when we insert new blocks we invalidate the cache. We thus had a long timeout, because we knew the cache would be automatically re-newed on insert. But it doesn't work for the `read-only` case, as we don't insert, we don't invalidate.

**Comment by simerplaha** [comment]
Hey @tdroxler, looking at this now. Think I've forgotten something about this issue from our chat. Can I please get a reminder of the problem here again?

Ran a test locally and here is what I understand so far.

In `readOnly` mode the `syncService` is disabled which means no writes are occurring right? Since the state of the database is not changing there shouldn't be a need to invalidate the cache?

Local test: I get 9413 for `select count(*) from block_headers where main_chain;` which is same in API.

![image](https://user-images.githubusercontent.com/1773953/162370006-82507758-6528-4731-85a2-6f7fe3a523b4.png)

Maybe in `readOnly` mode automatic expiration can be disabled all together?

**Comment by simerplaha** [comment]
Ok, I'm guessing there are two services running on the same database, one is `readOnly` and other is `readAndWrite`. In that case the cache in `readOnly` mode instance would need invalidating the count?

**Comment by tdroxler** [comment]
Yes both app are running on the same database. The `readOnly` get its cache invalidate by a timeout, so it's fine. I think I remember for the `read-write` app we were also invalidating while inserting new blocks right?
We discuss this with Cheng and we think we could afford to also let the `read-write` get invalidated by a timeout, no need to manually invalidate on insert. also we could raise the 5 seconds timeout, we don't need to have that level of live update. The questions is: what's a good timeout value? let's maybe start with 1 minutes and see how it performs.
The mean idea is to keep the same behavior for both read-only and read-write (just the sync services difference).
 WDYT?

**Comment by simerplaha** [comment]
> we were also invalidating while inserting new blocks right?

Yep. After new blocks are inserted.

> We discuss this with Cheng and we think we could afford to also let the read-write get invalidated by a timeout, no need to manually invalidate on insert.

I'm not sure because I would've gone the opposite direction - remove automatic invalidation and use to manual invalidation for `read-write` and enable automatic invalidation for `read-only` (5.seconds or ...).

Manual invalidation of data results in least error in the cache's output since we are explicitly saying "Hey Cache, there are new rows so update your count when the next read occurs" while being cheap on IO by not unnecessarily dispatching queries when no new rows were added. I might be missing something here because I don't understand the benefit of invalidating the cache after every 5 seconds (or any other timeout) ... 5.seconds timeouts in worst case will return error data for at most 5.seconds and it will cost more in terms of IO. For longer timeouts we would be paying for IO that might be unnecessary.

> The mean idea is to keep the same behavior for both read-only and read-write (just the sync services difference).

I guess if the main idea is to have the same behaviour/code for both states then the suggested change 👍🏼

**Comment by tdroxler** [comment]
block count is now using `AsyncReloadCache`,  it now also populate in read-only right? 

I think we can close this issue, don't hesitate to re-open if you feel the need.

**Comment by simerplaha** [comment]
Yep populates in read-only mode as well 👍🏼
