### ISSUE TITLE
Use partial index properly

### ISSUE THREAD

**Issue by polarker** [alephium/explorer-backend#191]
* an index for `main_chain` is a huge B-tree with 2 keys, this sounds weird
* alternatively, we create partial indexes for all relevant tables, to save storage size and improve performance (probably slightly)

@simerplaha do think we need to do a benchmark for this task? I am convinced intuitively :)

**Comment by simerplaha** [comment]
Here is the summary of new benchmarks. Hopefully helps confirm which way to proceed.

The outcome is still the same as other benchmarks in other PRs. From the many iterations I've executed (changing order of execution etc ...) I'm unable to definitively confirm which one is faster between full VS partial index. We already know we [save disk space](https://github.com/alephium/explorer-backend/issues/158#issuecomment-1077149490) with partial index.

# Benchmark types
- *NoIndex - With no index
- *FullIndex - Default basic index
- *Reset_10 - Eg: For `main_chain` this will create 1 row with `main_chain = true` for every 10 rows
- *Reset_100 - Eg: For `main_chain` this will create 1 row with `main_chain = true` for every 100 rows
- *Reset_1000 - Eg: For `main_chain` this will create 1 row with `main_chain = true` for every 1000 rows

# main_chain (boolean)

- Full index - `create index full_main_chain_idx on transactions (main_chain);`
- Partial index - `create index partial_main_chain_idx on transactions (main_chain) where main_chain = true;`
- Query benchmarked: `select count(*) from transactions where main_chain = true`

![image](https://user-images.githubusercontent.com/1773953/161744592-3cdc78f7-19a2-4ac6-9af7-e006a1c53727.png)

<details><summary>More benchmarks</summary>
<p>

![image](https://user-images.githubusercontent.com/1773953/161744670-3a82bdf6-6d8d-4d7a-b48c-6a702810a2c9.png)

![image](https://user-images.githubusercontent.com/1773953/161744685-812e93da-611f-4f37-84e9-c383f1e045dc.png)

</p>

</details>

# interval (integer)

- Full index - `create index full_interval_idx on transactions (interval);`
- Partial index - `create index partial_interval_idx on transactions (interval) where interval = 0;`
- Query benchmarked: `select count(*) from transactions where interval = 0`
- `*Reset` benchmarks set `interval` integer value incrementally and set to 0 for every new interval checkpoint. 

![image](https://user-images.githubusercontent.com/1773953/161745085-6b9e7745-b55c-49b4-82fa-61e7a5931fc0.png)

<details><summary>More benchmarks</summary>
<p>

![image](https://user-images.githubusercontent.com/1773953/161745122-1eca74e3-276b-4d6b-aeae-a8e7b817ae58.png)

![image](https://user-images.githubusercontent.com/1773953/161745144-02460215-4488-4f40-8f1e-43a88cc0fc35.png)

</p>

</details>

# Composite indexes

The ones you mentioned on Slack. 

- Full index - `create index full_composite_idx on transactions (tx_id, main_chain);`
- Partial index - `create index partial_composite_idx on transactions (tx_id) where main_chain = true;`
- Query benchmarked: `select * from transactions where tx_id = $txnId and main_chain = true;`

![image](https://user-images.githubusercontent.com/1773953/161745267-be55a08f-74d5-4dce-9243-22424c26bd04.png)

<details><summary>More benchmarks</summary>
<p>

![image](https://user-images.githubusercontent.com/1773953/161745296-cb88294b-c1a7-41b3-b4a1-df06cdc05b3a.png)

![image](https://user-images.githubusercontent.com/1773953/161745312-855d4169-499d-4fbf-a1b9-3f8777ccd988.png)

</p>

</details>

**Comment by polarker** [comment]
Thanks for the great benchmark ❤️  Let's go for `composite partial index` for storage size reduction.

**Comment by simerplaha** [comment]
Storage savings.

```sql
-- Current!
-- partial_main_chain_idx = 3168 kB
create index ... on table (main_chain) where (main_chain = true);
```

```sql
-- partial_composite_idx = 11 MB
create index ... on table (tx_id) where (main_chain = true);
```

```sql
-- 2 indexes partial_main_chain & txn_idx = 25 MB
create index ... on table (main_chain) where (main_chain = true);
create index ... on table (tx_id);
```

Do you want every query written so far re-checked and re-analysed if it would use the `composite_partial_idx` and also check that its is not slowing doing something else? Or keep the indexes the way it is and optimise only if there is a problem?

**Comment by polarker** [comment]
Agree that it's not urgent to improve this, so it's up to you to see when we should visit this.

**Comment by simerplaha** [comment]
Discussed with Thomas. Closing.
