### ISSUE TITLE
Fix flaky test-case `get tx by address`

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#192]
Test `TransactionQueriesSpec."get tx by address"` seems to be flaky.

On quick comparison it seems that two out of the three `Transaction`s have the same `TimeStamp` and sorting on `TimeStamp` fails equality (`is`) check.

[Build link](https://github.com/alephium/explorer-backend/runs/5810584026?check_suite_focus=true#step:5:148)

<details><summary>LOG</summary>
<p>

![image](https://user-images.githubusercontent.com/1773953/161477441-b0afbb80-d117-4aff-9277-218b4ead9c0d.png)

> [info] - should get tx hashes by address
[info] - should outpus for txs
[info] - should inputs for txs
[info] - should get tx by address *** FAILED ***
[info]   Vector(Transaction(d9bd388beaa92a9b32204adcccafc7241e65da9afadb6470d4ec8f27a91ea182,ff570d559083983b23bda3b203f7355c411a3a7461fb73c1709f8557d5e2d5c1,TimeStamp(1649053399249ms),List(),Vector(Output(0,Blake2b(hex"f4348fb88868eb2d702371a56659748301661c15b8ef215b581fe7c949180982"),1000000000000000000,AEmstyshzKRiiPs3j75TtuCPgJUxXtCvWWtMxLF8UjJt,None,None)),1,1000000000000000000), Transaction(4e0d778d832df1c6718515bc2ea5e984f6e8bb5c3646026026bd50f7e4088900,86c72f3d03f334f98651cee7b0b33dd49d971d9af159078d604c46d73e9a96d7,TimeStamp(1649053399249ms),List(),Vector(Output(0,Blake2b(hex"c346d0bbe8bb87403fa8d387225778504c03064000b94e40b55863e26d2cf4d0"),2000000000000000000,AEmstyshzKRiiPs3j75TtuCPgJUxXtCvWWtMxLF8UjJt,None,Some(8b468585485e39855f0948ed61544bbdb3aca79cec7edc39fb7402bec0f6f991))),1,1000000000000000000), Transaction(8b468585485e39855f0948ed61544bbdb3aca79cec7edc39fb7402bec0f6f991,793c2d8f1a9485f4928b2750bb6c43433184416d884873b8502a8f299911d74c,TimeStamp(1649048659249ms),Vector(Input(OutputRef(0,Blake2b(hex"c346d0bbe8bb87403fa8d387225778504c03064000b94e40b55863e26d2cf4d0")),None,4e0d778d832df1c6718515bc2ea5e984f6e8bb5c3646026026bd50f7e4088900,AEmstyshzKRiiPs3j75TtuCPgJUxXtCvWWtMxLF8UjJt,2000000000000000000)),Vector(Output(0,Blake2b(hex"c3a5dae2fd2d0f2773a27f7b03c5382d05729a55721d93531144e42876ff5e72"),3000000000000000000,FeuUt4KbqeSSUJ5nEmRTAfDJKKKruhrDyXkWHD3fRN7j,None,None)),1,1000000000000000000)) did not equal List(Transaction(4e0d778d832df1c6718515bc2ea5e984f6e8bb5c3646026026bd50f7e4088900,86c72f3d03f334f98651cee7b0b33dd49d971d9af159078d604c46d73e9a96d7,TimeStamp(1649053399249ms),List(),List(Output(0,Blake2b(hex"c346d0bbe8bb87403fa8d387225778504c03064000b94e40b55863e26d2cf4d0"),2000000000000000000,AEmstyshzKRiiPs3j75TtuCPgJUxXtCvWWtMxLF8UjJt,None,Some(8b468585485e39855f0948ed61544bbdb3aca79cec7edc39fb7402bec0f6f991))),1,1000000000000000000), Transaction(d9bd388beaa92a9b32204adcccafc7241e65da9afadb6470d4ec8f27a91ea182,ff570d559083983b23bda3b203f7355c411a3a7461fb73c1709f8557d5e2d5c1,TimeStamp(1649053399249ms),List(),List(Output(0,Blake2b(hex"f4348fb88868eb2d702371a56659748301661c15b8ef215b581fe7c949180982"),1000000000000000000,AEmstyshzKRiiPs3j75TtuCPgJUxXtCvWWtMxLF8UjJt,None,None)),1,1000000000000000000), Transaction(8b468585485e39855f0948ed61544bbdb3aca79cec7edc39fb7402bec0f6f991,793c2d8f1a9485f4928b2750bb6c43433184416d884873b8502a8f299911d74c,TimeStamp(1649048659249ms),List(Input(OutputRef(0,Blake2b(hex"c346d0bbe8bb87403fa8d387225778504c03064000b94e40b55863e26d2cf4d0")),None,4e0d778d832df1c6718515bc2ea5e984f6e8bb5c3646026026bd50f7e4088900,AEmstyshzKRiiPs3j75TtuCPgJUxXtCvWWtMxLF8UjJt,2000000000000000000)),List(Output(0,Blake2b(hex"c3a5dae2fd2d0f2773a27f7b03c5382d05729a55721d93531144e42876ff5e72"),3000000000000000000,FeuUt4KbqeSSUJ5nEmRTAfDJKKKruhrDyXkWHD3fRN7j,None,None)),1,1000000000000000000)) (TransactionQueriesSpec.scala:273)
[info]   Analysis:
[info]   Vector1(0: Transaction(d9bd388beaa92a9b32204adcccafc7241e65da9afadb6470d4ec8f27a91ea182,ff570d559083983b23bda3b203f7355c411a3a7461fb73c1709f8557d5e2d5c1,TimeStamp(1649053399249ms),List(),Vector(Output(0,Blake2b(hex"f4348fb88868eb2d702371a56659748301661c15b8ef215b581fe7c949180982"),1000000000000000000,AEmstyshzKRiiPs3j75TtuCPgJUxXtCvWWtMxLF8UjJt,None,None)),1,1000000000000000000) -> Transaction(4e0d778d832df1c6718515bc2ea5e984f6e8bb5c3646026026bd50f7e4088900,86c72f3d03f334f98651cee7b0b33dd49d971d9af159078d604c46d73e9a96d7,TimeStamp(1649053399249ms),List(),List(Output(0,Blake2b(hex"c346d0bbe8bb87403fa8d387225778504c03064000b94e40b55863e26d2cf4d0"),2000000000000000000,AEmstyshzKRiiPs3j75TtuCPgJUxXtCvWWtMxLF8UjJt,None,Some(8b468585485e39855f0948ed61544bbdb3aca79cec7edc39fb7402bec0f6f991))),1,1000000000000000000), 1: Transaction(4e0d778d832df1c6718515bc2ea5e984f6e8bb5c3646026026bd50f7e4088900,86c72f3d03f334f98651cee7b0b33dd49d971d9af159078d604c46d73e9a96d7,TimeStamp(1649053399249ms),List(),Vector(Output(0,Blake2b(hex"c346d0bbe8bb87403fa8d387225778504c03064000b94e40b55863e26d2cf4d0"),2000000000000000000,AEmstyshzKRiiPs3j75TtuCPgJUxXtCvWWtMxLF8UjJt,None,Some(8b468585485e39855f0948ed61544bbdb3aca79cec7edc39fb7402bec0f6f991))),1,1000000000000000000) -> Transaction(d9bd388beaa92a9b32204adcccafc7241e65da9afadb6470d4ec8f27a91ea182,ff570d559083983b23bda3b203f7355c411a3a7461fb73c1709f8557d5e2d5c1,TimeStamp(1649053399249ms),List(),List(Output(0,Blake2b(hex"f4348fb88868eb2d702371a56659748301661c15b8ef215b581fe7c949180982"),1000000000000000000,AEmstyshzKRiiPs3j75TtuCPgJUxXtCvWWtMxLF8UjJt,None,None)),1,1000000000000000000))
[info] - should output's spent info should only take the input from the main chain
[info] - should insert and ignore transactions
[info] - should return an empty list when not transactions are found - Isssue 174
[info] - should get total number of main transactions
2022-04-04 04:20:21,634 [-dispatcher-6] INFO  a.e.s.Slf4jLogger                      - Slf4jLogger started
[info] ReadWriteApplicationSpec:
2022-04-04 04:20:24,362 [-dispatcher-6] DEBUG o.a.e.s.MempoolSyncService$Impl        - Syncing mempol
2022-04-04 04:20:24,370 [-dispatcher-6] DEBUG o.a.e.s.TokenSupplyService$Impl        - Computing token supply
</p>

</details>

**Comment by tdroxler** [comment]
is this issue still relevant @simerplaha or we can close?

**Comment by simerplaha** [comment]
Saw this test fail in my last PR and Cheng's `Upgrade to leman8` PR. Think it's still relevant.
