### ISSUE TITLE
Configurable logging

### ISSUE THREAD

**Issue by polarker** [alephium/explorer-backend#196]

**Comment by killerwhile** [comment]
Ideally, log verbosity should be configurable at startup via an environment variable, and at runtime using a REST endpoint (or similar).
The rationale behind changing the verbosity at runtime is to allow debugging a process in a degraded state without requiring a restart of the process, i.e. resetting the state.

**Comment by polarker** [comment]
> The rationale behind changing the verbosity at runtime is to allow debugging a process in a degraded state without requiring a restart of the process, i.e. resetting the state.

Interesting practice! I guess we will need to support this for full node as well.
