### ISSUE TITLE
Sanity check for the latest deployment

### ISSUE THREAD

**Issue by polarker** [alephium/explorer-backend#216]
Let's see if everything goes well

**Comment by polarker** [comment]
I suggest that we have a shell script to 1) sample random address from the database; 2) query the balance of the address and compare it to full node's balance.

We could try this for many many addresses

**Comment by tdroxler** [comment]
>I suggest that we have a shell script to 1) sample random address from the database; 2) query the balance of the address and compare it to full node's balance.

great idea.

**Comment by tdroxler** [comment]
Sanity check has been run successfully :+1:
