### ISSUE TITLE
Handle system termination (`sys.exit`) gracefully

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#246]
Currently `sys.exit(...)` in invoked at a few places making those function untestable. 

System termination should be centralised and should happen after all services are closed properly instead of abrupt jvm termination. 

Also check for alternate solution to system termination. Is halting sync services and alerting admins (email or whatever) of invalid state enough instead of jvm termination?

**Comment by polarker** [comment]
We will need to sync with Benoit. As far as I see, we could
* for fatal errors, we log them, terminate the system, and let docker restart the application automatically
* for non-fatal errors, logging it properly should be enough

**Comment by tdroxler** [comment]
Had a call yesterday with Benoît and I created #243 from ops side it's always better to restart on fatal-error instead of trying to recover.
