### ISSUE TITLE
Introduce Tokens

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#247]
We want to introduce and show tokens into the explorer, this will also be used by the wallet.

A few interesting endpoints we could implement:

### Address' tokens endpoints 

* List token ids (with balance? for a given user)
```
/addresses/<user_addr>/tokens
```

* Give the balance of a given token for a given address
```
/addresses/<user_addr>/tokens/<token_id>/balance
```

* list all transactions of the token for a specific user.
```
/addresses/<user_addr>/tokens/<token_id>/transactions
```

### Tokens endpoints 

* list all token ids
```
/tokens
```

* list all of the transactions of a token (is it interesting?)
```
/tokens/<token_id>/transactions
```
* list address having a token (is it interesting?)
```
/tokens/<token_id>/addresses
```

* Return info of a given token, we could extract information from the contract state, but it’s impossible to validate the information
We could also maintain a list of know tokens.
```
/tokens/<token_id>/info
```

@mvaivre : Which endpoints do you think are useful/needed for your explorer and wallet idea on tokens? Do you see missing ones?

### Implementation 

* We currently see two ways: 

1. We add `token_id` column in our schemas and consider `null` when we're talking on pure ALPH.
2. We introduce new tables that are the same as the others, but with the `token_id` more.

* Probably the first approach is the easiest and cleanest, but might introduce performance issue due to the extra column/index?
This will need to be dig in while starting the integration, it's hard now to tell if one solution has big issue.

* We might need to add a new table `TransactionPerTokens` table, unless is clean to add this to `TransactionPerAddresses`.

* We will need to re-sync from scratch, so maybe we should take the opportunity to break few stuff, one thing I have in mind is now to make the difference between `AssetOutput` and `ContractOutput`, we can probably keep it backward compatible with the front-end, but at least we'll have the data in our DB. Let's review our models to see if we miss something.

* Probably we'll use `alephium-1.4.0` models and wait for the hard-fork to happen before releasing/deploying this feature? HDYT @polarker

**Comment by mvaivre** [comment]
> List token ids (with balance? for a given user)

Yes, having the balance would be great.

> list all transactions of the token for a specific user.

Do we consider to update the traditional `/addresses/<user_addr>/transactions` to show transactions of any kind of assets?

> list all of the transactions of a token (is it interesting?)

Yes, this can be useful! In etherscan, you have a token page listing all transactions, see [here](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7). We could plan to do the same.

> list address having a token (is it interesting?)

Yes, also interesting for stats purposes. Etherscan gives access to the [1000 top addresses](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7#balances).

> We could also maintain a list of know tokens.

This is a question I asked myself. I think this would be nice to be able to show a logo, a description, maybe a website. In etherscan, you can edit the token info if you manage to validate those criterion :

<img width="490" alt="image" src="https://user-images.githubusercontent.com/6715943/170041530-5e2732cc-4c00-43fb-89dd-aea469099662.png">

BTW, [here's](https://www.figma.com/file/7SiG11k6DJiSRvysd2Kadw/Alephium-Explorer?node-id=485%3A201) a little sneak peak of what we could do ;)

**Comment by tdroxler** [comment]
> Yes, having the balance would be great.

:+1: I'll keep you updated if it's too heavy or not.
 
> Do we consider to update the traditional /addresses/<user_addr>/transactions to show transactions of any kind of assets?

Yes the tokens will be added to this endpoint, they will be part of an `Output` [ the same way it's done in the node](https://github.com/alephium/alephium/blob/dbf80f41c73e58532d190a1aab4e3f443659f23f/api/src/main/scala/org/alephium/api/model/Output.scala#L31) 

I'll start digging and prototyping :rocket: (need first to create a token in devnet ^^)

**Comment by polarker** [comment]
> Probably we'll use alephium-1.4.0 models and wait for the hard-fork to happen before releasing/deploying this feature? HDYT @polarker

We will need this feature before hardfork due to all of the ongoing and upcoming dApp projects. Once we deploy Wormhole bridge, it would be nice to query wrapped tokens.

> This is a question I asked myself. I think this would be nice to be able to show a logo, a description, maybe a website. In etherscan, you can edit the token info if you manage to validate those criterion :

We could also maintain a repo on Github like the following projects, and ask people to send PRs to register a new coin.
SLIP44: https://github.com/satoshilabs/slips/blob/master/slip-0044.md
Solana: https://github.com/solana-labs/token-list
Avalanche's DEX: https://github.com/pangolindex/tokenlists

**Comment by tdroxler** [comment]
Small progress on the tokens: I experimented a lot in this commit https://github.com/alephium/explorer-backend/commit/b35036e5374b8cac323c929eeaa0cdb38517ac24
I already wrote most of the endpoints to validate I can properly use the new DB schemas. 
Here is my proposition:

* In our current `OutputSchema` we add a [tokens column](https://github.com/alephium/explorer-backend/blob/b35036e5374b8cac323c929eeaa0cdb38517ac24/app/src/main/scala/org/alephium/explorer/persistence/schema/OutputSchema.scala#L42) which is a bytestring representation of the tokens list. Like this the data is stored and easy to grab to return the tokens in our `Output`, so we can easily represent a transaction as it is returned by the node. I also took the opportunity to make the difference between [AssetOutput and ContractOutput](https://github.com/alephium/explorer-backend/blob/b35036e5374b8cac323c929eeaa0cdb38517ac24/app/src/main/scala/org/alephium/explorer/api/model/Output.scala#L27-L59)

* For handling address' tokens balance, spent tokens etc, we introduce a [new token-outputs table](https://github.com/alephium/explorer-backend/blob/b35036e5374b8cac323c929eeaa0cdb38517ac24/app/src/main/scala/org/alephium/explorer/persistence/schema/TokenOutputSchema.scala#L32-L50), which is basically the same as the Output table, but representing only tokens (not the ALPH). This table [can be joined with the input table](https://github.com/alephium/explorer-backend/blob/b35036e5374b8cac323c929eeaa0cdb38517ac24/app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala#L330-L348), the same way we do to get the ALPH balance, so no need to add a `TokenInput` table IMO.

* To speed up some other endpoints, we can introduce a [token-transactions-per-address table](https://github.com/alephium/explorer-backend/blob/b35036e5374b8cac323c929eeaa0cdb38517ac24/app/src/main/scala/org/alephium/explorer/persistence/schema/TokenPerAddressSchema.scala#L28-L38) the same way we have the `transactions-per-address` table.

I think with those changes we can cover all our above needs.

I'm still not surehow to handle the tokens' info, does a new table make sense to make SQL request against it or a simple file is enough? not sure yet.

**Comment by tdroxler** [comment]
Small update, I have a [working solution](https://github.com/alephium/explorer-backend/commit/7c11d4f95706812434e0f15616eb6d4b177bb64b)

We decided that the token info could be store in repo as suggested by Cheng and the front-end could get the info directly from that file. So I won't implement `/tokens/<token_id>/info` in this PR.
All other endpoints are implemented.
In the end I added 4 new table, to avoid heavy query:

`token_outputs`: used in 
```
/addresses/<user_addr>/tokens/<token_id>/balance
/addresses/<user_addr>/tokens/<token_id>/transactions
```
`token_per_addresses`: used in
```
/addresses/<user_addr>/tokens/<token_id>/transactions
/tokens/<token_id>/addresses
```
`transaction_per_token` used in:
```
/tokens/<token_id>/transactions
```
`token_info`: to keep a list of existing tokens, currently stored only with a `last-used` field to help the ordering, used in:
```
/tokens
```` 

I now "just" need to write test :sweat_smile:  and clean a bit the code. I'll do my best but not sure I'll manage to nicely split my PR in small nice commit, sorry in advance for that.

I'm not sure yet, but I might merge this work (once PR is created/reviewed/approved) in a `dev` branch and deploy it on a testnet env, so front-end could experiment with it and suggest stuff, as it will require a full re-sync, better not pushing it blindly to prod on first merge, if suddenly we need some adjustment in the db.

**Comment by tdroxler** [comment]
Following a question on #264 you can get the following network with only a few blocks and 2-3 txs with a token to make your tests.
[network-2-tokens.zip](https://github.com/alephium/explorer-backend/files/8897559/network-2-tokens.zip)
just copy the content in your `.alephium` (be careful not to override YOUR `user.conf`)
Otherwise you an use the [Testnet](https://wiki.alephium.org/testnet-and-devnet/Testnet-Guide/) which also has few tokens.
cc/ @mvaivre @nop33

**Comment by nop33** [comment]
@tdroxler I am using the testnet (https://testnet-wallet.alephium.org, https://testnet-backend.alephium.org), could you send me some tokens to `1hdKRKgs6bzRPxXqEbg2zXEBGDyoS5EJaCnwKw4i9pi3`, please? Thanks!

**Comment by tdroxler** [comment]
hum I don't have any tokens on the testnet (don't know who created them), but I can create one. I'll create a wallet and maybe you can send me some ALPH so I can create a token?

**Comment by tdroxler** [comment]
Tokens are currently deployed in staging here: https://mainnet-explorer-v18-0-backend.alephium.org/

**Comment by simerplaha** [comment]
Hey Thomas, I'm getting `404` 

![image](https://user-images.githubusercontent.com/1773953/182759663-cc7b0083-5344-49e0-9650-e03af13bb64b.png)

**Comment by tdroxler** [comment]
yes we have no route at root,  but that's a good point, maybe we should redirect to https://mainnet-explorer-v18-0-backend.alephium.org/infos ?

**Comment by simerplaha** [comment]
Ah of course. Silly me.

Yea good idea. 

Bit of a long shot - But it'd be pretty cool to have some sort of API explorer.
