### ISSUE TITLE
Add `close` to `EndpointSender` in `alephium-http` jar dependency

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#259]
`EndpointSender` is missing `close` API so there is no way to shutdown `BlockFlowClient`'s sttp client. 

Boot-up failures in PR #255 will not shutdown the JVM because sttp keeps the `Thread` alive.

I've added a commit to this issue to show calling [close in the client](https://github.com/alephium/explorer-backend/commit/240f586f753a1ae769456fcd765dd0de1aa4803b#diff-09e969ecf11f3aa10e8c12c2bf2c91b64ddcc2be147652097cb2e7e4b73b15d4R100) via private method invocation/reflection.

Or is there another way to close the client?

**Comment by tdroxler** [comment]
done in 1.4.1
