### ISSUE TITLE
Migrate to vertx

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#270]
to get rid of akka-http and follow what we have in the full node.

**Comment by simerplaha** [comment]
To save duplicating work, maybe a part of #256 can be implemented in this issue or we can implement this after #256. 

We kinda should decouple explorer APIs from the http-server we use. Vertx, Akka-http or whatever should only know about a single function it needs to call per route.  Currently all routes have to know about everything it needs to execute a request - `ExecutionContext`, `DatabaseConfig`, `*Cache`, `*Service` etc and are therefore stateful.

We need `ExplorerAPI` that exposes only the public APIs to be used by the http-server. Makes testing easier, test-cases in `ApplicationSpec/ExplorerSpec` will be typed.

**Comment by tdroxler** [comment]
good idea to separate a bit. I need to check if we can test an [Endpoint](https://github.com/alephium/explorer-backend/blob/abe41362cf13d2f7bf2face5a251d0e060eaadb6/app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala#L35-L39) without it's [serverLogic](https://github.com/alephium/explorer-backend/blob/abe41362cf13d2f7bf2face5a251d0e060eaadb6/app/src/main/scala/org/alephium/explorer/web/AddressServer.scala#L42-L47)
