### ISSUE TITLE
Update release workflow to support more platform

### ISSUE THREAD

**Issue by polarker** [alephium/explorer-backend#273]
`sbt docker` does not build images for arches like Apple M1. Let's use the same workflow as `alephium`.

ref: https://github.com/alephium/alephium/blob/master/.github/workflows/docker-buildx.yml

**Comment by polarker** [comment]
I label this as high-priority because the whole docker stack will be used for dApp development on different OS soon.

**Comment by tdroxler** [comment]
do we still need this one https://github.com/alephium/alephium/blob/master/.github/workflows/docker.yml ?

**Comment by polarker** [comment]
> do we still need this one https://github.com/alephium/alephium/blob/master/.github/workflows/docker.yml ?

For the full node, we publish regular docker images for each merged PR to `dev-alephium` docker-hub using `docker.yml`. We publish docker images for new releases using `docker-buildx.yml`.

For explorer-backend, it's probably enough to publish docker images for new releases.

**Comment by tdroxler** [comment]
This is actually very practical to have images for each merged,  I could more easily test stuff on staging, I haven't notice we were pushing on every merge, very cool :+1:
