### ISSUE TITLE
Add proper cache for some of the queries

### ISSUE THREAD

**Issue by polarker** [alephium/explorer-backend#281]
Some of the key points:
* Ideally, if one refreshes a page on explorer, BE tries to fetch data from caches as much as possible
* For immutable data (e.g. block, tx), we could just use LRU cache
* For ephemeral data, we might use a short expiration duration for the cache if a bit latency is not a problem
* Caffeine cache should be enough for our purpose
* Good to have for the long term (low priority): configuration for the cache size, an endpoint to refresh all of the caches, cache metrics

@tdroxler @simerplaha I am not sure the priority of this, so I don't label it for now. As far as I remember, we have other cache tasks created, this one could be the main task.

**Comment by tdroxler** [comment]
We already introduced cache, we probably forgot to close that task.
