### ISSUE TITLE
Typed `AppStateSchema`

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#293]
`AppStateSchema` can be type-safe. Currently we use `String` and `ByteString`.

```scala
AppStateSchema.table.insertOrUpdate(AppState("last_finalized_input_time", serialize(time)))
```

If Slick allows for it, this should be type-safe to something like the following:
```scala
AppStateSchema.table.insertOrUpdate(LastFinalizedInputTime(time))
```
Priority: Low.

**Comment by tdroxler** [comment]
Great idea
