### ISSUE TITLE
Provide endpoint to fetch list of transactions for a list of addresses

### ISSUE THREAD

**Issue by nop33** [alephium/explorer-backend#299]
In the desktop wallet the pagination of the transaction list of the overview page is problematic.

When first rendering the Overview page, we fetch the transactions page 1 of each address of the wallet, then we merge this list, and we sort it by date. When clicking "Load more" we fetch the transactions page 2 of each address, merge the data with the previous one and sort them again. This might cause the following issue: A transaction of address X of page 2 might have an earlier date than a transaction of address Y of page 1, causing a reshuffling of the transaction list, which is bad UX.

I would like to ask if it's possible to have an endpoint on backend that returns the list of transactions for a set of addresses so that we can easily paginate it. Same way we have an endpoint to fetch a (sorted by date) paginated list of transactions for an address, I'd like the same for a list of addresses.

**Comment by nop33** [comment]
In which version will this feature be available? Cheers!

**Comment by tdroxler** [comment]
I guess I could release `1.9.1` now so you can start playing with this or it's fine for you to `sbt app/run` master?

**Comment by tdroxler** [comment]
it will be there next release, which should be hopefully soon :tm:
