### ISSUE TITLE
Disable `inline` logs from build log output 

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#324]
Inline logs fill up the CI build log output.

We should probably disable logging for all builds and enable manually when debugging?

**Comment by tdroxler** [comment]
mmmm can't we just disable inline logs? 

When something is flaky it's convenient to have the logs right away, as it doesn't always fail.

**Comment by simerplaha** [comment]
> mmmm can't we just disable inline logs?

Yep. That's exactly what the issue is suggesting. Titled: Disable `inline` logs.

**Comment by tdroxler** [comment]
oh I thought you were proposing to remove ALL logs :sweat_smile:
