### ISSUE TITLE
Unconfirmed txs per address endpoint

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#326]
We want to be able to retrieve the unconfirmed txs for a given address. The purpose is with our different wallets, when we send a tx we gray it out until it's confirmed, but if you close the wallet during that period, the tx won't show when re-opening if it's still unconfirmed.

As discussed in [this PR](https://github.com/alephium/explorer-backend/pull/320) We miss a proper way to search the unconfirmed inputs for a user.

in the branch [feature/uinput-address](https://github.com/alephium/explorer-backend/tree/feature/uinput-address) I'm experimenting with a readable `UnlockScript`, which is part of the input.

`UnlockScript` can have 3 types:

- P2PKH: pay to public key hash, the classic one address makes a transfer
- P2MPKH: pay to multiple key hash: ALPH are sent from a multisig address.
- P2SH: pay to script hash: when a script is transfering hash.

In the branch I now have those 3 models implemented and the `Input` and `UInput` now have a field `unlockScript`
```
 "unlockScript": {
        "type": "p2pkh",
        "address": "14PqtYSSbwpUi2RJKUvv9yUwGafd6yHbEcke7ionuiE7w"
      }
```
```
 "unlockScript": {
        "type": "p2mpkh",
        "indexedAddresses": [{
           "address": "14PqtYSSbwpUi2RJKUvv9yUwGafd6yHbEcke7ionuiE7w",
           "index": 0
            },{
           "address": "152qtYSSbwpUi2RJKUvv9yUwGafd6yHbEcke7ion34TT",
           "index": 1
        }]
      }
```
```
 "unlockScript": {
        "type": "p2sh",
        "script": "<some_hex_string",
        "params": "<some_hex_string"
      }
```

Our wallets case is only interested in `p2pkh`, we could maybe add an endpoint:

`/addresses/<address>/p2pkh-unconfirmed-transactions`

WDYT @nop33

**Comment by nop33** [comment]
For now, yes, the wallets only care about P2PKH unconfirmed txs. However, soon™ our wallets will be able to call smart contracts. Would that fall into the P2SH case?

**Comment by tdroxler** [comment]
From the wallet you will make a transaction toward a smart contract, this fall in the `UnlockScript.P2PKH`, because you are spending a `Output` which is locked by a `LockupScript.P2PKH`  and then maybe the smart contract will make some tx on it's own and this will be `P2SH` as it using it's own `Output`.

So I don't think we will need to deal with `P2SH` tx from the wallet.

**Comment by tdroxler** [comment]
just pinging @polarker to confirm what I just said

**Comment by tdroxler** [comment]
maybe we could add `UnlockScript` to our node api models too,[ currently it's only a ByteString](https://github.com/alephium/alephium/blob/220dfd96a7dbb0672ec89ce81d56801b33172923/api/src/main/scala/org/alephium/api/model/AssetInput.scala#L25)

**Comment by polarker** [comment]
I did not notice this important task. Did we investigated how this is done for BTC and Ergo?
