### ISSUE TITLE
Reduce number of queries dispatched by `getLocalMaxTimestamp` 

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#328]
One of the first queries executed by sync is [`getLocalMaxTimestamp`](https://github.com/alephium/explorer-backend/blob/master/app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala#L181) to calculate maximum `height` and `timestamp`. Both these fields are in `block_headers` table. 

But the query dispatches a number of other queries accessing multiple tables `transactions`, `block_deps`, `outputs`, `inputs` which are not needed other than just `block_headers`

Incase I'm overlooking something. Is this a valid issue? @tdroxler 

## Example un-tested query

Query to maybe use instead (un-tested)

```sql
SELECT (max(block_timestamp),
        sum(height),
        height)
FROM block_headers
WHERE chain_from = 1
  AND chain_to = 4
  AND height = (SELECT max(height)
                from block_headers
                WHERE chain_from = 1
                  AND chain_to = 4)
group by height;
```

## Use `UNION`

[The function](https://github.com/alephium/explorer-backend/blob/master/app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala#L181) also traverses over multiple groups and queries them concurrently which can be replaced with `UNION`.

**Comment by tdroxler** [comment]
daaaaamn you so right, that's the disadvantage to access data through the DAO only :/

Maybe we could give access to the DB directly or add new functions to the DAO.

That's a super nice catch :rocket:  I'll dig the code for more thing like that

**Comment by tdroxler** [comment]
We also use `BlockDao.maxHeight` a lot, which could be replace using the `BlockCache`

**Comment by tdroxler** [comment]
damn, [here](https://github.com/alephium/explorer-backend/blob/v1.8.0-rc1/app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala#L280-L281) also we could use `getLite`.

The more and more I'm thinking of all this, the more I think we could be closer to the DB in the `BlockFlowSyncService`.
This is by far our heaviest sync service and we could maybe gain some perf to work directly with some `DBAction` rather than going trough `Future` in the BlockDao.

WDYT @simerplaha ?

**Comment by simerplaha** [comment]
Yea totally! You are right. 

There are places here where we can squeeze out decent performance. 

Would you be ok if I worked on this issue? It kinda helps me understand whats needed for #204. The one that I'm working on right now #242 is sorta dependant on #134. And #134 is kinda related to this issue. 

Working on #242 right now might be premature.

**Comment by tdroxler** [comment]
Sure go ahead :rocket:
