### ISSUE TITLE
Introduce a `SyncOnly` application

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#337]
Split the code so we can have two applications: 

One to do synchronization only and  one ReadOnly that exposes the endpoints.

We still want to be able to launch a `ReadWriteApplication` as today.

**Comment by simerplaha** [comment]
Hey Thomas, couple of questions. 

By _'Split the code'_ I'm assuming you mean we need a configuration that allows the following three types of startups?
- `ReadOnly` - Like the current setting `read-only = true`
- `ReadAndSync` - Like the current setting `read-only = false`
- `SyncOnly` - New guy

In `SyncOnly` 
- I guess the Http server should not be started? No http server means more resources for Sync is the motivation here I think. 
- Do you also want any one of the services (excluding `BlowFlowSyncService`) disabled in `SyncOnly` mode?
- Anything else?

**Comment by tdroxler** [comment]
Yep exactly for the 3 scenario.

for the `SyncOnly`, we indeed want to disable the http service and let only all sync services. I think the idea is later to run on our AWS only a `SyncOnly` and several `ReadOnly`, right @killerwhile ?

But we need to keep a `ReadWrite` so we can propose an easy way to run the explorer.

Now regarding the `SyncOnly`, @killerwhile if we disable the http server we won't be able to change the logging level on the fly, is it ok?

**Comment by killerwhile** [comment]
Yes deployment target is one `SyncOnly` and as many `ReadOnly` as needed.
Changing log level at runtime was rarely used, I think it's not a show stopper for now.
