### ISSUE TITLE
Smart contract events support

### ISSUE THREAD

**Issue by polarker** [alephium/explorer-backend#344]
Details to be added.

@tdroxler Please feel free to reminder me if I forgot to discuss with you next week.

**Comment by polarker** [comment]
Here is a draft proposal to enable to support:
1. Full node has an endpoint to query all contract events based on block hash. This index is disabled by default.
2. For each block hash, the explorer backend needs to sync both the block and the respective contract events. Explorer backend will persist events in the DB.
a. For each event, we create such indexes `(block hash, tx id, contract address, unique input address)`.
b. For simplicity, transactions with multiple input addresses will not be indexed.
3. Users could query for all of the events with parameters: `(contract address, user address)`

**Comment by tdroxler** [comment]
When I sync a block, is there a way to know if this block has events or not? it could light the syncing process if we query the events only when necessary.

**Comment by polarker** [comment]
> When I sync a block, is there a way to know if this block has events or not? it could light the syncing process if we query the events only when necessary.

There is no shortcut, but I could add a new endpoint `blockflow/blocks-with-events/{block-hash}` to fetch blocks and events in one shot. WDYT?

**Comment by tdroxler** [comment]
That could be nice to light both the node and the explorer.

**Comment by tdroxler** [comment]
when you say `input address` it's the address(es) in the `Val.Address` fields?

**Comment by polarker** [comment]
> when you say `input address` it's the address(es) in the `Val.Address` fields?

By `input address`, I meant the address of TX inputs.

The address fields in the events are the contract addresses that emit the events. Which is another thing I will explain to you in more details later.
