### ISSUE TITLE
Remove double reading a `block` in `BlockFlowSyncService.insert`

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#358]
Function call to [`updateMainMain`](https://github.com/alephium/explorer-backend/blob/master/app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala#L279) should process the already read `parentBlock` instead  of fetching the same block again from the database in [`BlockDao.updateMainChain`](https://github.com/alephium/explorer-backend/blob/master/app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala#L113).

The asserts [`assert(block.chainFrom == chainFrom && block.chainTo == chainTo)`](https://github.com/alephium/explorer-backend/blob/master/app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala#L116) and the check for [`!block.mainChain`](https://github.com/alephium/explorer-backend/blob/master/app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala#L115) are also not required (by the current `sync` thread) as it's already confirmed by [`BlockFlowSyncService.insert`](https://github.com/alephium/explorer-backend/blob/master/app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala#L275).

Parent issue: #350

@tdroxler please confirm, is this a valid issue?

**Comment by tdroxler** [comment]
definitively, I think the idea was to make `BlockDao.updateMainChainAction` safe and usable by everyone, but it seems it's used just by the `BlockFlowSyncService` so we could definitively improve few things.

**Comment by simerplaha** [comment]
Temporarily closing this. PR #369 has changed the story here. 

Will reopen if needed as sync optimisations (#343) progress.
