### ISSUE TITLE
Returns unconfirmed transactions TOWARD the given address

### ISSUE THREAD

**Issue by LeeAlephium** [alephium/explorer-backend#360]
I did a testnet test with @sven-hash and it was clear that for some reason, the endpoint is not returning their unconfirmed transaction. When I send funds to addresses within the same wallet, the endpoint works, but their transactions to me always returned an empty list. I had desktop-wallet checking this endpoint every 5 seconds and manually looking at the Network tab output and it never appeared.

Big thanks again to @sven-hash for the sudden request to test, it was very helpful for this :heart: 

This is using the new `addresses/<address>/unconfirmed-transactions` endpoint

**Comment by nop33** [comment]
I’ve been testing on testnet (https://wallet-v18.testnet.alephium.org, https://backend-v18.testnet.alephium.org) all day, sending funds to internal wallet addresses and external addresses, and apart from long waiting times, I did not have any issues. All pending txs were immediately displayed when starting the wallet and were confirmed after a while.

**Comment by tdroxler** [comment]
ooh I think what @LeeAlephium is saying is that transaction from an external address toward his address is not working.
Currently it's expected, the current endpoint returns transaction FROM the address, but not yet TO the address.
I thought we only wanted the FROM case, but discussing with Mika, we said it could be fun to see the txs than we are suppose to receive.

**Comment by LeeAlephium** [comment]
@tdroxler exactly.

**Comment by tdroxler** [comment]
I'll change the title of the issue so we know what to implement
