### ISSUE TITLE
Centralise direct basic database queries in our test-cases to `TestQueries` object

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#368]
Updated:  3/11/2022

In our test-cases we directly access tables (`*Schema.table`) to access data.

For example:

```scala
run(BlockHeaderSchema.table ++= blockHeaders).futureValue
run(BlockHeaderSchema.table.delete).futureValue
run(BlockHeaderSchema.table.result).futureValue
run(BlockHeaderSchema.table.length.result).futureValue
```

Be nice to centralise even these basic table operations to the `TestQueries` object so we do not create a dependency on the target DB library we use everywhere in our test-cases.

**Comment by tdroxler** [comment]
very good point, this would indeed ease a lot if one day we want to try another DB lib.

**Comment by simerplaha** [comment]
Discussed this. And the current way is more convenient over creating dedicated functions in `TestQueries` which requires all `insert` and `delete` functions to be properly named because the compiler doesn't not allow overloading them which will be a pain in the a$$.

Preferring convenience of usage for now.

As the decision to use a SQL library (#355) progresses, this can be considered then.
