### ISSUE TITLE
Add tapir streaming support

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#374]
for [this task](https://github.com/alephium/explorer/issues/41) as it could require to fetch a lot of data, it could be nice to add some streaming support, unfortunately it's currently blocked by: https://github.com/softwaremill/tapir/issues/2533

**Comment by tdroxler** [comment]
good progress here: I manage to add streaming for [our vertx server interpreter](https://github.com/tdroxler/tapir/commit/7bb761f6135d927588ccf6f0fb699a1dc660c3b0)
I did tried this with in our code base [here](https://github.com/alephium/explorer-backend/commit/d703af491980a4050e10ac2f865b8d01ceb7c5bf) and it seems to work.

Still a long way to have something clean (also need to get in merge in tapir ^^)

**Comment by tdroxler** [comment]
Progress of the day, I spent the all morning trying to use [the vertx streams](https://vertx.io/docs/vertx-reactive-streams/java/) withouth success...Way to javaish with callback, cannot `map` the data etc etc.... It then took me 15min and [10 lines of code](https://github.com/alephium/explorer-backend/blob/f5906097899c1dbf01b77f6e23c9a6cd28ba8428/app/src/main/scala/org/alephium/explorer/service/TransactionService.scala#L110-L119) to make it works with `akka-streams`. 
I guess I made my choice :sweat_smile: 
the current ugly progress is in [this branch](https://github.com/alephium/explorer-backend/tree/feature/streaming-report)

What's nice is that we can only work with `Publisher` and `Subscriber` from ReactiveStreams and then use what ever lib we want. Using akka-streams won't block us into it.

**Comment by polarker** [comment]
`3.3G of txs` on http is impressive 😅
