### ISSUE TITLE
Stop the app in case of an exception in PSQL or in our sync services

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#395]
Currently if a fatal error happen in our sync services, the app won't stop. Those stateless services are scheduled by the `Scheduler` and on an error we only log, but then it get stuck.

We better stop the all app and let it restart.

**Comment by simerplaha** [comment]
> We better stop the all app and let it restart

Just checking, is this suggesting that we terminate the jvm?

**Comment by tdroxler** [comment]
yes I think it's safer, we could imagine to re-schedule the failed service, but if the issue is "un-fixable" then we'll be in a infinite loop of retries and adding a limit of retry seems a bit over-kill compare to just crash the app and let the devOps do their magic :)

**Comment by simerplaha** [comment]
Yep makes sense 👍🏼 .

Kinda wish we didn't have to though :( because as you know it doesn't look good. Terminating the VM as a solution to a problem and relying on devops to resolve it.

But maybe I'm overlooking something and an exit is needed.

**Comment by tdroxler** [comment]
Of course we need to also fix every errors that could occurs, like those [deadlocks](https://github.com/alephium/explorer-backend/issues/323#issuecomment-1328500829) (thx for the nice new investigations btw), but for some others where we can't do anything, like PG not accessible anymore, it's probably better to crash the app.
