### ISSUE TITLE
Nodes are not synchronized after upgrading 1.11.0

### ISSUE THREAD

**Issue by COLUD4** [alephium/explorer-backend#407]

**Comment by COLUD4** [comment]
<img width="1067" alt="截屏2022-12-10 19 40 16" src="https://user-images.githubusercontent.com/21240219/206853213-305944e3-08c4-4011-b661-fb9766f43ff2.png">
<img width="1107" alt="截屏2022-12-10 19 40 31" src="https://user-images.githubusercontent.com/21240219/206853214-420d7c42-46d1-407e-a2df-90ea8ce239d2.png">

**Comment by COLUD4** [comment]
After upgrading the node after 1.11.0, the api cannot read the new synchronized height

**Comment by polarker** [comment]
@COLUD4 Thanks for reporting. The backend team will work on this on Monday!

**Comment by tdroxler** [comment]
> it seems the backend is migrating the database.

Yes exactly, from `1.10` to `1.11` there is an heavy migration that takes around 1-2h. If you wait enough, everything should be fine :) 

Can you tell us if it's the case? so we can close this issue.

Thx

**Comment by tdroxler** [comment]
@COLUD4 I'm closing this issue, don't hesitate to re-open it if needed.
