### ISSUE TITLE
Update queries spliced literal values to be parametric queries

### ISSUE THREAD

**Issue by simerplaha** [alephium/explorer-backend#426]
The following queries are using spliced literal values (`#$param`). They can be updated to be parameterised queries so they are used as Prepared Statements better.

# Paginated queries

This is a relatively recent change so want to confirm if this is something we'd want changed?

```scala
#${pagination.query}
```

The problem here is that because [Pagination.limit](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/api/model/Pagination.scala#L21) is being embedded in the following paginated queries as `String` value instead of query parameters, this reduces the chance of these queries being used as Prepared Statements for cases where `limit` and `offset` differ between subsequent queries. So locally the client will not be able to cache these queries well & will have to recompile and also the server will also not be able to cache 'em well.

- [TokenQueries.listTokensAction](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/TokenQueries.scala#L71)
- [TokenQueries.getAddressesByToken](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/TokenQueries.scala#L88)
- [TokenQueries.listTokenTransactionsAction](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/TokenQueries.scala#L100)
- [TokenQueries.getTokenTxHashesByAddressQuery](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/TokenQueries.scala#L130)
- [TransactionQueries.getTxHashesByBlockHashWithPaginationQuery](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala#L141)
- [TransactionQueries.getTxHashesByAddressQuerySQLNoJoin](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala#L159)
- [TransactionQueries.getTxHashesByAddressQuerySQLNoJoinTimeRanged](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala#L222)
- [UnconfirmedTransactionQueries.listPaginatedUnconfirmedTransactionsQuery](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/UnconfirmedTransactionQueries.scala#L53)
- [TokenSupplyService.listTokenSupply](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala#L111)
- Plus 12 other queries

# `reservedAddresses`

- [TokenSupplyService.circulatingTokensOptionQuery](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala#L156)
- [TokenSupplyService.reservedTokensOptionQuery](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala#L191)
- [TokenSupplyService.lockedTokensOptionQuery](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala#L210)

# Others

Some of the following queries might be deprecated and replaced with their `*NoJoin` equivalent. So double check if they are in use before making any changes. 

- [HashrateQueries.computeHashratesAndInsert](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/HashrateQueries.scala#L56)
- [HashrateQueries.computeHashrateRawString](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/HashrateQueries.scala#L119)
- [TransactionQueries.gasFromTxsSQL](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala#L383)
- [InputQueries.inputsFromTxsSQL](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/InputQueries.scala#L101)
- [InputQueries.inputsFromTxsSQLAS](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/InputQueries.scala#L125)
- [OutputQueries.outputsFromTxsSQL](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/OutputQueries.scala#L322)
- [OutputQueries.outputsFromTxsSQLAS](https://github.com/alephium/explorer-backend/blob/56f8d97990a6eb99a86b8a8b37951b13d59b975b/app/src/main/scala/org/alephium/explorer/persistence/queries/OutputQueries.scala#L322)

**Comment by tdroxler** [comment]
`pagination` has been done.
Question @simerplaha for the `reservedAddresses`, as [it's a val and isn't a parametric thing](https://github.com/alephium/explorer-backend/blob/dee22e5faa2735068a839c04dc060deb8f079bf1/app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala#L78-L79) do we need a parametric query?
The query will always be the same, addresses are like hardcoded in the query.

**Comment by simerplaha** [comment]
Oh, yes! You are right. Fixed parameters don't have to be parametric. I'm basing this on [these notes](https://github.com/alephium/explorer-backend/issues/137#issuecomment-1036109562) from over a year ago. 

According to those notes, static queries are cacheable, and since `reservedAddresses` is a static string, it does not have to be parametric.

`HashrateQueries` could still benefit from being parametric since `dateGroup` is not static and has two possible variations.

**Comment by tdroxler** [comment]
yes it has 2 possible variations, but the 2 variations will be cached no?

**Comment by simerplaha** [comment]
Yes, both variations will be cached. All queries are cached when they are called the 5<sup>th</sup> time because `prepareThreshold = 5`.

**Comment by tdroxler** [comment]
I gave a try to parametrize `dateGroup`, but it's a part of a query, not a value. It seems impossible, or a least not clean at all. As it will be cached anyway let's keep it like this.
I think we tackled all the queries, closing the issue :rocket:
