### ISSUE TITLE
`GET:/addresses/{address}/unconfirmed-transactions` returns `TransactionLike[]` and not  UnconfirmedTransaction[]?

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#427]
`GET:/addresses/{address}/unconfirmed-transactions` returns `TransactionLike[]` and not `UnconfirmedTransaction[]`

`UnconfirmedTransaction` is extending `TransactionLike` and thus has a `type` field in his JSON schema.
If we try to return directly `UnconfirmedTransaction` in an endpoint, `tapir` doesn't understand we want the same schema and is creating a new `UnconfirmedTransaction1` schema in the `openapi.yaml`, withouth the `type` field.

It would be nicer if the above endpoint in the `openapi.yaml` could return the `UnconfirmedTransaction` with the `type` field. So we could have only 1 schema for it.

The other solution is to define a new type, the same way we do the separation of `Transaction` and `ConfirmedTransaction`. But we need to think of a good naming to avoid confusion.

**Comment by nop33** [comment]
`MempoolTransaction`? 😅

**Comment by tdroxler** [comment]
could be an idea yes, but then we should maybe rename the endpoint too?

**Comment by nop33** [comment]
Just to verify, unconfirmed transactions are the ones that have not yet been included in a block? They are just in the mempool, awaiting to be added in a block. Right?

**Comment by tdroxler** [comment]
yes exactly

**Comment by nop33** [comment]
Since that's the case, `MempoolTransaction` and `GET:/addresses/{address}/mempool-transactions` sounds good to me 👍 

I'll let @mvaivre give his opinion as well.

**Comment by tdroxler** [comment]
but then it means that `TransactionLike` will still be `ConfirmedTransaction` and `UnconfirmedTransaction`

**Comment by nop33** [comment]
imo, this could be a better naming convention:
```ts
type Transaction = ConfirmedTransaction | UnconfirmedTransaction
```

**Comment by tdroxler** [comment]
ahah but `Transaction` is already taken to avoid having `Transaction1` :stuck_out_tongue_closed_eyes:  anyway I need to figure how to go around that issue in `tapir`

**Comment by mvaivre** [comment]
Yeah, basically the solution is to solve the issue in `tapir` otherwise we'll go around in circles 😝 (ie. using a new `MempoolTransaction` type will make things even more confusing if `TransactionLike` is still `ConfirmedTransaction | UnconfirmedTransaction`).

When the issue if fixed, we could still decide to use `MempoolTransaction` instead of `UnconfirmedTransaction`. Maybe the former is a bit more precise, technically speaking.

**Comment by nop33** [comment]
What's even more confusing is that there is `Transaction` and `ConfirmedTransaction` 😅

**Comment by tdroxler** [comment]
>What's even more confusing is that there is Transaction and ConfirmedTransaction sweat_smile 

Yes totally  agree, ideally I would like to have only 
```scala
type Transaction = ConfirmedTransaction | UnconfirmedTransaction
```
as you proposed.

**Comment by tdroxler** [comment]
As done in [this PR](https://github.com/alephium/explorer-backend/pull/431), we currently can't have only `Transaction` as in my previous comment. So after few discussion we decided to go with :

 *   Transaction
 *   MempoolTransaction
 *  TransactionLike = AccpetedTransaction | PendingTransaction


Where
```
  Transaction        = AccpetedTransaction
  MempoolTransaction = PendingTransaction
```

**Comment by nop33** [comment]
I hope you mean `AcceptedTransaction` and not `AccpetedTransaction` 😇 

Thanks for the clarification!

**Comment by tdroxler** [comment]
yes sorry :) [the code is the truth](https://github.com/alephium/explorer-backend/blob/15f30e931b521eea2121c98576fd71da88457d78/app/src/main/scala/org/alephium/explorer/api/model/TransactionLike.scala#L38-L39)

**Comment by tdroxler** [comment]
closing as https://github.com/alephium/explorer-backend/pull/431 is merged. All `mempool` endpoints are now returning a proper `MempoolTransaction` type
