### ISSUE TITLE
Provide supported market tokens through an openapi enum 

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#512]
currently we have the list in our config:https://github.com/alephium/explorer-backend/blob/5780248bde5b5323ff9846af88be8ddb3b41a380/app/src/main/resources/application.conf#L68-L90 

This could be useful if we were also exposing that list through the openapi.

cc @mvaivre

**Comment by mvaivre** [comment]
@tdroxler any update on this one? We're still using a hard coded constant on our side.

**Comment by tdroxler** [comment]
I'll try to have a look very soon
