### ISSUE TITLE
Integrate data from Mobula.io for price related endpoints

### ISSUE THREAD

**Issue by nop33** [alephium/explorer-backend#557]
As discussed on Slack, we want to start using Mobula as our primary source of ALPH and token prices, with Coingecko being the backup option. We want to use the explorer backend as a proxy to avoid being rate-limited.

Related issue:
- https://github.com/alephium/alephium-frontend/issues/693

Related resources:
- https://docs.mobula.io/

**Comment by mvaivre** [comment]
We have multiple projects pushing to get their token price visible in our wallets cc @MaudSimon 

This would be great to start looking into this soon :)
