### ISSUE TITLE
Improve `TokenSupplyService`

### ISSUE THREAD

**Issue by tdroxler** [alephium/explorer-backend#86]
* We could probably cache the genesis blocks as we always query the same
* `unspentTokens` function can be very slow with millions of utxos
* The syncPeriod should be adaptive, when we know computed all supply, we can wait for 1 all day.

**Comment by tdroxler** [comment]
We changed how we count the token supply recently, not sure the description is still relevant, but let's keep the issue so we check.

**Comment by tdroxler** [comment]
We could now probably get rid of the `JOIN` in our token supply queries, as we are now updating the inputs with the output ref info. But we need to be sure we only compute token supply when the inputs are updated.

**Comment by tdroxler** [comment]
`spent_finalized` isn't inserted either because when we insert an output it can't be spent yet, but while writing I realize we should insert both value anyway even if it's None most of the time, we don't know in the future if suddenly we'll insert spent outputs. Nice catch

**Comment by simerplaha** [comment]
I think the test-cases couldn't pick this up because the generator [`outputEntityGen`](https://github.com/alephium/explorer-backend/blob/token-supply-improvement/app/src/test/scala/org/alephium/explorer/Generators.scala#L532C11-L533) always default these fields to `None`.

**Comment by tdroxler** [comment]
> I think the test-cases couldn't pick this up because the generator [`outputEntityGen`](https://github.com/alephium/explorer-backend/blob/token-supply-improvement/app/src/test/scala/org/alephium/explorer/Generators.scala#L532C11-L533) always default these fields to `None`.

good point, I'll add a test for that case

**Comment by tdroxler** [comment]
> I think the test-cases couldn't pick this up because the generator [`outputEntityGen`](https://github.com/alephium/explorer-backend/blob/token-supply-improvement/app/src/test/scala/org/alephium/explorer/Generators.scala#L532C11-L533) always default these fields to `None`.

done in [this commit ](https://github.com/alephium/explorer-backend/pull/470/commits/bcf47f2626b740c3540c1f5685f97a086cc196d4) You'll see it in [this PR](https://github.com/alephium/explorer-backend/pull/470/commits)

**Comment by tdroxler** [comment]
done in https://github.com/alephium/explorer-backend/pull/470
