### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by killerwhile** [alephium/explorer-backend#94]
Explorer backend should report prometheus-compatible metrics.

Using a different port than the API might be good, so the metrics would not be publicly exposed.

Main metrics I'm looking for

- Requests counter, also by status code
- Requests time
- DB queries counter 
- DB queries time, also by family (SELECT, UPDATE, INSERT, ...)

**Comment by tdroxler** [comment]
Discussed with @killerwhile we can close it.
